# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'theSauceIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for theSauceIOS
    
   pod 'Firebase/Core'
   pod 'Firebase/Auth'
   pod 'Firebase/Database'
   pod 'Firebase/Storage'

  target 'theSauceIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'theSauceIOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
